/*
 * This file is generated by jOOQ.
 */
package ydb.default_schema;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ydb.DefaultCatalog;
import ydb.default_schema.tables.Episodes;
import ydb.default_schema.tables.Seasons;
import ydb.default_schema.tables.Series;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>DEFAULT_SCHEMA.episodes</code>.
     */
    public final Episodes EPISODES = Episodes.EPISODES;

    /**
     * The table <code>DEFAULT_SCHEMA.seasons</code>.
     */
    public final Seasons SEASONS = Seasons.SEASONS;

    /**
     * The table <code>DEFAULT_SCHEMA.series</code>.
     */
    public final Series SERIES = Series.SERIES;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("DEFAULT_SCHEMA", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Episodes.EPISODES,
            Seasons.SEASONS,
            Series.SERIES
        );
    }
}
