/*
 * This file is generated by jOOQ.
 */
package ydb.default_schema;


import ydb.default_schema.tables.Episodes;
import ydb.default_schema.tables.Seasons;
import ydb.default_schema.tables.Series;


/**
 * Convenience access to all tables in DEFAULT_SCHEMA.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>DEFAULT_SCHEMA.episodes</code>.
     */
    public static final Episodes EPISODES = Episodes.EPISODES;

    /**
     * The table <code>DEFAULT_SCHEMA.seasons</code>.
     */
    public static final Seasons SEASONS = Seasons.SEASONS;

    /**
     * The table <code>DEFAULT_SCHEMA.series</code>.
     */
    public static final Series SERIES = Series.SERIES;
}
