app.connection=grpc://ydb:2136/local
app.threadsCount=32
app.workload.duration=180
app.rpsLimit=-1
app.otel.enabled=true
app.otel.endpoint=http://otel-collector:4317
app.otel.serviceName=ydb-token-app
