/*
 * This file is generated by jOOQ.
 */
package ydb.default_schema.tables.records;


import java.time.LocalDate;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;

import ydb.default_schema.tables.Episodes;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EpisodesRecord extends UpdatableRecordImpl<EpisodesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DEFAULT_SCHEMA.episodes.series_id</code>.
     */
    public void setSeriesId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.episodes.series_id</code>.
     */
    public Long getSeriesId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.episodes.season_id</code>.
     */
    public void setSeasonId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.episodes.season_id</code>.
     */
    public Long getSeasonId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.episodes.episode_id</code>.
     */
    public void setEpisodeId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.episodes.episode_id</code>.
     */
    public Long getEpisodeId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.episodes.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.episodes.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.episodes.air_date</code>.
     */
    public void setAirDate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.episodes.air_date</code>.
     */
    public LocalDate getAirDate() {
        return (LocalDate) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Long, Long, Long> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EpisodesRecord
     */
    public EpisodesRecord() {
        super(Episodes.EPISODES);
    }

    /**
     * Create a detached, initialised EpisodesRecord
     */
    public EpisodesRecord(Long seriesId, Long seasonId, Long episodeId, String title, LocalDate airDate) {
        super(Episodes.EPISODES);

        setSeriesId(seriesId);
        setSeasonId(seasonId);
        setEpisodeId(episodeId);
        setTitle(title);
        setAirDate(airDate);
        resetChangedOnNotNull();
    }
}
