/*
 * This file is generated by jOOQ.
 */
package ydb.default_schema.tables.records;


import java.time.LocalDate;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import ydb.default_schema.tables.Seasons;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SeasonsRecord extends UpdatableRecordImpl<SeasonsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DEFAULT_SCHEMA.seasons.series_id</code>.
     */
    public void setSeriesId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.seasons.series_id</code>.
     */
    public Long getSeriesId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.seasons.season_id</code>.
     */
    public void setSeasonId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.seasons.season_id</code>.
     */
    public Long getSeasonId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.seasons.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.seasons.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.seasons.first_aired</code>.
     */
    public void setFirstAired(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.seasons.first_aired</code>.
     */
    public LocalDate getFirstAired() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>DEFAULT_SCHEMA.seasons.last_aired</code>.
     */
    public void setLastAired(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>DEFAULT_SCHEMA.seasons.last_aired</code>.
     */
    public LocalDate getLastAired() {
        return (LocalDate) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeasonsRecord
     */
    public SeasonsRecord() {
        super(Seasons.SEASONS);
    }

    /**
     * Create a detached, initialised SeasonsRecord
     */
    public SeasonsRecord(Long seriesId, Long seasonId, String title, LocalDate firstAired, LocalDate lastAired) {
        super(Seasons.SEASONS);

        setSeriesId(seriesId);
        setSeasonId(seasonId);
        setTitle(title);
        setFirstAired(firstAired);
        setLastAired(lastAired);
        resetChangedOnNotNull();
    }
}
